import { Noto_Sans, Noto_Sans_JP, Noto_Nastaliq_Urdu } from "next/font/google"

import styles from "app/main.module.scss";
import "app/main.scss";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "800"],
  display: "swap"
})
const NotoJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "800"],
  display: "swap"
})
const NotoNum = Noto_Nastaliq_Urdu({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap"
})

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body>
        <main className={`${styles.wrapper} ${NotoJP.className}`} >
          {children}
        </main>
      </body>
    </html>
  )
}
